version = 0.1
[default.deploy.parameters]
stack_name = "next-market-ddb-sam"
resolve_s3 = true
s3_prefix = "next-market-ddb-sam"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
